[package]
name = "rust_proxy_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
reqwest = "0.11.7"
futures = "0.3.18"
tokio = { version = "1.14.0", features = ["full"] }
